export interface WorkerData {
  id: string;
  name: string;
  age: number;
  gender: string;
  location: string;
  workType: string;
  workHoursPerDay: number;
  daysPerWeek: number;
  nightShift: boolean;
  ppeUsage: boolean;
  protectiveGearCondition: string;
  exposureLevel: string;
  hasHealthInsurance: boolean;
  lastCheckupDate: string;
  knownConditions: string[];
  airQualityIndex: number;
  incomeLevel: string;
  accessToCleanWater: boolean;
  healthRiskCategory: 'Low' | 'Medium' | 'High';
}

export const mockData: WorkerData[] = [
  {
    id: "W001",
    name: "Ravi Kumar",
    age: 35,
    gender: "Male",
    location: "Delhi",
    workType: "Sewage Cleaner",
    workHoursPerDay: 8,
    daysPerWeek: 6,
    nightShift: false,
    ppeUsage: true,
    protectiveGearCondition: "Worn",
    exposureLevel: "High",
    hasHealthInsurance: false,
    lastCheckupDate: "2024-12-20",
    knownConditions: ["Asthma"],
    airQualityIndex: 220,
    incomeLevel: "Low",
    accessToCleanWater: false,
    healthRiskCategory: "High",
  },
  {
    id: "W002",
    name: "Sunita Devi",
    age: 29,
    gender: "Female",
    location: "Mumbai",
    workType: "Dry Waste Picker",
    workHoursPerDay: 6,
    daysPerWeek: 5,
    nightShift: false,
    ppeUsage: true,
    protectiveGearCondition: "Good",
    exposureLevel: "Medium",
    hasHealthInsurance: true,
    lastCheckupDate: "2025-02-15",
    knownConditions: [],
    airQualityIndex: 180,
    incomeLevel: "Medium",
    accessToCleanWater: true,
    healthRiskCategory: "Medium",
  },
  {
    id: "W003",
    name: "Karan Singh",
    age: 48,
    gender: "Male",
    location: "Lucknow",
    workType: "Biomedical Waste Collector",
    workHoursPerDay: 9,
    daysPerWeek: 6,
    nightShift: true,
    ppeUsage: false,
    protectiveGearCondition: "None",
    exposureLevel: "Very High",
    hasHealthInsurance: false,
    lastCheckupDate: "2023-11-11",
    knownConditions: ["Hepatitis B"],
    airQualityIndex: 250,
    incomeLevel: "Low",
    accessToCleanWater: false,
    healthRiskCategory: "High",
  },
  {
    id: "W004",
    name: "Anjali Sharma",
    age: 32,
    gender: "Female",
    location: "Chennai",
    workType: "Wet Waste Picker",
    workHoursPerDay: 7,
    daysPerWeek: 6,
    nightShift: false,
    ppeUsage: true,
    protectiveGearCondition: "Fair",
    exposureLevel: "High",
    hasHealthInsurance: true,
    lastCheckupDate: "2024-07-15",
    knownConditions: ["Skin Allergy"],
    airQualityIndex: 160,
    incomeLevel: "Low",
    accessToCleanWater: true,
    healthRiskCategory: "Medium",
  },
  {
    id: "W005",
    name: "Mohammad Azhar",
    age: 40,
    gender: "Male",
    location: "Patna",
    workType: "Drain Cleaner",
    workHoursPerDay: 10,
    daysPerWeek: 7,
    nightShift: true,
    ppeUsage: false,
    protectiveGearCondition: "None",
    exposureLevel: "Very High",
    hasHealthInsurance: false,
    lastCheckupDate: "2022-09-10",
    knownConditions: ["TB"],
    airQualityIndex: 300,
    incomeLevel: "Low",
    accessToCleanWater: false,
    healthRiskCategory: "High",
  },
  {
    id: "W006",
    name: "Rekha Patil",
    age: 26,
    gender: "Female",
    location: "Nagpur",
    workType: "Electronic Waste Handler",
    workHoursPerDay: 6,
    daysPerWeek: 5,
    nightShift: false,
    ppeUsage: true,
    protectiveGearCondition: "Good",
    exposureLevel: "Medium",
    hasHealthInsurance: true,
    lastCheckupDate: "2025-05-01",
    knownConditions: [],
    airQualityIndex: 130,
    incomeLevel: "Medium",
    accessToCleanWater: true,
    healthRiskCategory: "Low",
  },
  {
    id: "W007",
    name: "Suresh Rathi",
    age: 55,
    gender: "Male",
    location: "Jaipur",
    workType: "River Cleaner",
    workHoursPerDay: 8,
    daysPerWeek: 6,
    nightShift: false,
    ppeUsage: false,
    protectiveGearCondition: "None",
    exposureLevel: "High",
    hasHealthInsurance: false,
    lastCheckupDate: "2023-06-12",
    knownConditions: ["Diabetes"],
    airQualityIndex: 200,
    incomeLevel: "Low",
    accessToCleanWater: false,
    healthRiskCategory: "High",
  },
  {
  id: "W008",
  name: "Deepak Meena",
  age: 38,
  gender: "Male",
  location: "Bhopal",
  workType: "Garbage Truck Driver",
  workHoursPerDay: 8,
  daysPerWeek: 6,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Fair",
  exposureLevel: "Medium",
  hasHealthInsurance: false,
  lastCheckupDate: "2025-01-20",
  knownConditions: [],
  airQualityIndex: 170,
  incomeLevel: "Medium",
  accessToCleanWater: true,
  healthRiskCategory: "Medium",
},
{
  id: "W009",
  name: "Lata Joshi",
  age: 42,
  gender: "Female",
  location: "Ahmedabad",
  workType: "Street Sweeper",
  workHoursPerDay: 9,
  daysPerWeek: 7,
  nightShift: true,
  ppeUsage: false,
  protectiveGearCondition: "Worn",
  exposureLevel: "Very High",
  hasHealthInsurance: false,
  lastCheckupDate: "2023-10-10",
  knownConditions: ["Arthritis"],
  airQualityIndex: 210,
  incomeLevel: "Low",
  accessToCleanWater: false,
  healthRiskCategory: "High",
},
{
  id: "W010",
  name: "Arjun Verma",
  age: 30,
  gender: "Male",
  location: "Hyderabad",
  workType: "Plastic Waste Sorter",
  workHoursPerDay: 7,
  daysPerWeek: 6,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Good",
  exposureLevel: "Medium",
  hasHealthInsurance: true,
  lastCheckupDate: "2025-04-10",
  knownConditions: [],
  airQualityIndex: 150,
  incomeLevel: "Medium",
  accessToCleanWater: true,
  healthRiskCategory: "Medium",
},
{
  id: "W011",
  name: "Farida Sheikh",
  age: 36,
  gender: "Female",
  location: "Kolkata",
  workType: "Manual Scavenger",
  workHoursPerDay: 10,
  daysPerWeek: 7,
  nightShift: false,
  ppeUsage: false,
  protectiveGearCondition: "None",
  exposureLevel: "Very High",
  hasHealthInsurance: false,
  lastCheckupDate: "2022-05-14",
  knownConditions: ["Skin Infections", "Back Pain"],
  airQualityIndex: 260,
  incomeLevel: "Low",
  accessToCleanWater: false,
  healthRiskCategory: "High",
},
{
  id: "W012",
  name: "Rajesh Pawar",
  age: 28,
  gender: "Male",
  location: "Pune",
  workType: "Construction Debris Collector",
  workHoursPerDay: 8,
  daysPerWeek: 5,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Good",
  exposureLevel: "Medium",
  hasHealthInsurance: true,
  lastCheckupDate: "2024-11-25",
  knownConditions: [],
  airQualityIndex: 140,
  incomeLevel: "Medium",
  accessToCleanWater: true,
  healthRiskCategory: "Low",
},
{
  id: "W013",
  name: "Meena Kumari",
  age: 31,
  gender: "Female",
  location: "Surat",
  workType: "Compost Handler",
  workHoursPerDay: 6,
  daysPerWeek: 6,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Fair",
  exposureLevel: "Medium",
  hasHealthInsurance: false,
  lastCheckupDate: "2025-03-15",
  knownConditions: [],
  airQualityIndex: 120,
  incomeLevel: "Low",
  accessToCleanWater: true,
  healthRiskCategory: "Medium",
},
{
  id: "W014",
  name: "Nitin Rawat",
  age: 45,
  gender: "Male",
  location: "Dehradun",
  workType: "Drain Desilting Worker",
  workHoursPerDay: 9,
  daysPerWeek: 6,
  nightShift: false,
  ppeUsage: false,
  protectiveGearCondition: "Worn",
  exposureLevel: "High",
  hasHealthInsurance: false,
  lastCheckupDate: "2023-07-09",
  knownConditions: ["Hypertension"],
  airQualityIndex: 190,
  incomeLevel: "Low",
  accessToCleanWater: false,
  healthRiskCategory: "High",
},
{
  id: "W015",
  name: "Alka Bhosale",
  age: 33,
  gender: "Female",
  location: "Nashik",
  workType: "Medical Waste Transporter",
  workHoursPerDay: 7,
  daysPerWeek: 5,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Good",
  exposureLevel: "Medium",
  hasHealthInsurance: true,
  lastCheckupDate: "2025-06-01",
  knownConditions: [],
  airQualityIndex: 110,
  incomeLevel: "Medium",
  accessToCleanWater: true,
  healthRiskCategory: "Low",
},
{
  id: "W016",
  name: "Pradeep Sinha",
  age: 51,
  gender: "Male",
  location: "Varanasi",
  workType: "Incineration Plant Operator",
  workHoursPerDay: 8,
  daysPerWeek: 6,
  nightShift: true,
  ppeUsage: true,
  protectiveGearCondition: "Fair",
  exposureLevel: "High",
  hasHealthInsurance: false,
  lastCheckupDate: "2024-09-10",
  knownConditions: ["Asthma"],
  airQualityIndex: 230,
  incomeLevel: "Low",
  accessToCleanWater: false,
  healthRiskCategory: "High",
},
{
  id: "W017",
  name: "Pooja Yadav",
  age: 27,
  gender: "Female",
  location: "Noida",
  workType: "Recyclable Collector",
  workHoursPerDay: 6,
  daysPerWeek: 5,
  nightShift: false,
  ppeUsage: true,
  protectiveGearCondition: "Good",
  exposureLevel: "Low",
  hasHealthInsurance: true,
  lastCheckupDate: "2025-01-10",
  knownConditions: [],
  airQualityIndex: 100,
  incomeLevel: "Medium",
  accessToCleanWater: true,
  healthRiskCategory: "Low",
}

];

// ✅ Function to add new worker
export const addWorker = (worker: WorkerData) => {
  mockData.push(worker);
};
